apiVersion: v1
kind: Service
metadata:
  name: books-service
spec:
  # Expose the service on a static port on each node
  # so that we can access the service from outside the cluster
  type: LoadBalancer

  # When the node receives a request on the static port (30163)
  # "select pods with the label 'app' set to 'echo-hostname'"
  # and forward the request to one of them
  selector:
    app: books-services-app
  ports:
    # Three types of ports for a service
    # nodePort - a static port assigned on each the node
    # port - port exposed internally in the cluster
    # targetPort - the container port to send requests to
    - port: 9090
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: services-deployment
  labels:
    app: books-services-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: books-services-app
  template:
    metadata:
      labels:
        app: books-services-app
    spec:
      containers:
        - name: services-backend
          image: ppatel21/spring-rest-hello-world:42
          ports:
            - containerPort: 8080
