---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: services-deployment
  labels:
    app: web
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: services-backend
          image: ppatel21/spring-rest-hello-world:41
          ports:
            - containerPort: 5050
